# https://taskfile.dev

version: '3'

vars:
  DBFILE: chinook.db

tasks:
  default:
    cmds:
      - cp -f ../{{.DBFILE}} .
      - go run main.go
      - echo "SELECT * FROM artists WHERE ArtistId=999" | sqlite3 -header -table ./{{.DBFILE}}
