# https://taskfile.dev

version: '3'

vars:
  DBFILE: ../chinook.db

tasks:
  default:
    cmds:
      - go run main.go
      - echo "SELECT * FROM artists WHERE ArtistId=999" | sqlite3 -header -table {{.DBFILE}}
      - echo "DELETE FROM artists WHERE ArtistId=999" | sqlite3 -header -table {{.DBFILE}}
