
image: gitpod/workspace-go:latest
tasks:
  - name: initial
    init:
      go install github.com/go-task/task/v3/cmd/task@latest &&
      go install honnef.co/go/tools/cmd/staticcheck@latest &&
      go install golang.org/x/tools/cmd/goimports@latest &&
      go install github.com/mgechev/revive@latest &&
      go install github.com/go-delve/delve/cmd/dlv@latest &&
      go install go.uber.org/nilaway/cmd/nilaway@latest
  - name: prepare
    command: task download

vscode:
  extensions:
    - golang.go
