# https://taskfile.dev

version: '3'

vars:
  DB: chinook.db
  URL: https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

tasks:
  download:
    preconditions:
      - (! test -f {{.DB}})
    cmds:
      - wget "{{.URL}}"
      - unzip -o chinook.zip
      - rm -f chinook.zip
      - go mod download
    silent: true
    ignore_error: true
  vet:
    cmds:
      - go vet ./...
      - staticcheck ./...
    ignore_error: true
